import pandas as pd

# Mappa di correzione
auto_makers = {
    'TOYT SCION': 'Toyota',
    'CARRY ON': 'N/A',
    'MIMI': 'N/A',
    'OPTIMA': 'N/A',
    'APRILIA': 'N/A',
    'HYUNA': 'Hyundai',
    'STRG': 'N/A',
    'THOMAS BUILT': 'N/A',
    'LAND OVER': 'Land Rover',
    'VANH': 'N/A',
    'VOVLVO': 'Volvo',
    'TELSA': 'Tesla',
    'HIUNDAY': 'Hyundai',
    'MOTSUBISHI': 'Mitsubishi',
    'HONDTK': 'Honda',
    'CHEVF': 'Chevrolet',
    'CAAB': 'N/A',
    'BNZ': 'Mercedes-Benz',
    'FREIGHTL': 'N/A',
    'MERK': 'Mercedes-Benz',
    'LND RVR': 'Land Rover',
    'JEFF': 'N/A',
    'HYANDUI': 'Hyundai',
    'AOTAO': 'N/A',
    'LNDROVER': 'Land Rover',
    'VADILAC': 'N/A',
    'SIEN': 'N/A',
    'MAST': 'N/A',
    'ZHEJIANG KAIKAI': 'N/A',
    'VOLKVAL': 'Volkswagen',
    'TOMAS': 'N/A',
    'GENUINE': 'N/A',
    'HONF': 'Honda',
    'TAIZHOU CITY': 'N/A',
    'AUI': 'Audi',
    'MAZD SW': 'Mazda',
    'PONT4S': 'Pontiac',
    'ACRU': 'Acura',
    'CCC': 'N/A',
    'DCION': 'Scion',
    'ACUARA': 'Acura',
    'LAND RVR': 'Land Rover',
    'MOTIVE': 'N/A',
    'INFINIITI': 'Infinity',
    'DODGVAL2006': 'Dodge',
    'NIFINITI': 'Infinity',
    'MERB': 'Mercedes-Benz',
    'FTLR': 'N/A',
    'ROCK': 'N/A',
    'P0NTIAC': 'Pontiac',
    'TOYYOTA': 'Toyota',
    'SATUN': 'Saturn',
    'INFIINITI': 'Infinity',
    'VOLKWGON': 'Volkswagen',
    'KAWI': 'Kawasaki',
    'PERO': 'N/A',
    'MASDIA': 'Mazda',
    'TOW': 'N/A',
    'ROLLS ROYCE': 'Rolls Royce',
    'UHAUL': 'N/A',
    'DORD': 'N/A',
    'INFINITYQ': 'Infinity',
    'MERZD': 'Mercedes-Benz',
    'THOMAS BUS': 'N/A',
    'VOLKSWAGKON': 'Volkswagen',
    'INGINITY': 'Infinity',
    'VOLVVAL2005': 'Volvo',
    'CHECVY': 'Chevrolet',
    'SUKU': 'N/A',
    'Q': 'N/A',
    'LANDVAL2012': 'Land Rover',
    'INFIINITI': 'Infinity',
    'BUICJ': 'Buick',
    'SATARN': 'Saturn',
    'KYCO': 'N/A',
    'HTUN': 'N/A',
    'SUPER HORNET': 'N/A',
    'PETER': 'N/A',
    'FREIGHLNR': 'N/A',
    'HYYUNDAI': 'Hyundai',
    'LEONARD': 'N/A',
    'MERCVAL1993': 'Mercedes-Benz',
    'MERX': 'Mercedes-Benz',
    'NNT': 'N/A',
    'CHEVVAL2008': 'Chevrolet',
    'BECK': 'N/A',
    'MERCBZ': 'Mercedes-Benz',
    'PILOT': 'Honda',
    'NISSANS': 'Nissan',
    'HEIL': 'N/A',
    'VOLKSWAGGON': 'Volkswagen',
    'CHEVVAL2002': 'Chevrolet',
    'MERCVAL2012': 'Mercedes-Benz',
    'NAZDA': 'Mazda',
    'MITA': 'N/A',
    'MIN': 'Mini',
    'MERV': 'N/A',
    'F150': 'Ford',
    'LEXUXS': 'Lexus',
    'INIFINIT': 'Infinity',
    'ABY': 'N/A',
    'KRYSTAL': 'N/A',
    'MISTUSUBISHI': 'Mitsubishi',
    'MARM': 'N/A',
    'OLKSWAGON': 'Volkswagen',
    'FORDVAL2012': 'Ford',
    'INFIVAL': 'Infinity',
    'SHOR': 'N/A',
    'DAEWOOD': 'N/A',
    'MISSIBISHI': 'Mitsubishi',
    'MISTU': 'Mitsubishi',
    'AUDU': 'Audi',
    'MERCUR': 'Mercury',
    'VO;K': 'Volvo',
    'KIA4': 'Kia',
    'TYG': 'N/A',
    'MSAERADI': 'N/A',
    'NOSSAN': 'Nissan',
    'CRYSL': 'Chrysler',
    'NP': 'N/A',
    'HEVY': 'Chevrolet',
    'NISSIAM': 'Nissan',
    'RIO': 'Kia',
    'XTRE': 'N/A',
    'TEST': 'N/A',
    'CADILLA': 'Cadillac',
    'VWOLKS': 'Volkswagen',
    'CADI;AC': 'Cadillac',
    'LEXUS4D': 'Lexus',
    'LEXUVAL2011': 'Lexus',
    'RNG ROV': 'Range Rover',
    'UTILITY': 'N/A',
    'CADDILIAC': 'Cadillac',
    'HONSA': 'Honda',
    'CHEVROLOET': 'Chevrolet',
    'HYUNVAL2013': 'Hyundai',
    'HYUNDAIA': 'Hyundai',
    'KENILWORTH': 'N/A',
    'VKW': 'N/A',
    'WESTERN': 'N/A',
    'ACUA': 'Acura',
    'MAYB': 'N/A',
    'MER-BENZ': 'Mercedes-Benz',
    'TOYOVAL1999': 'Toyota',
    'CADAILLIC': 'Cadillac',
    'TYTA': 'Toyota',
    'SMARVAL2010': 'N/A',
    'CAI': 'N/A',
    'EXUS': 'Lexus',
    'OUTBACK': 'Subaru',
    'HYUNUNDAI': 'Hyundai',
    'TESCA': 'Tesla',
    'KENIWORTH': 'Kenworth',
    'ISSU': 'N/A',
    'LAMBO': 'Lamborghini',
    'VOLSKWAGON': 'Volkswagen',
    'FORN': 'Ford',
    'MAZDVAL2015': 'Mazda',
    'KAWKISI': 'Kawasaki',
    'MITSUBUISHI': 'Mitsubishi',
    'MITSUIBISHI': 'Mitsubishi',
    'INTERNATION': 'International',
    'LINCOL': 'Lincoln',
    'SLINGSHOT': 'N/A',
    'CHVORLET': 'Chevrolet',
    'EPO': 'N/A',
    'BMWVAL2015': 'BMW',
    'SUZUIKI': 'Suzuki',
    'CHEVROLOET': 'Chevrolet',
    'SUSBARU': 'Subaru',
    'FANGYUE': 'N/A',
    'CIDI': 'N/A',
    'JIFF': 'N/A',
    'CHYRSTLER': 'Chrysler',
    'TOYOTO': 'Toyota',
    'TOYOVAL2010': 'Toyota',
    'E350': 'Ford',
    'MITSUBISUI': 'Mitsubishi',
    'HOMEMADE': 'N/A',
    'KAWASAWKI': 'Kawasaki',
    'HONDACIVIC': 'Honda',
    'MAZDZ': 'Mazda',
    'HONDVAL2005': 'Honda',
    'MCLAREN': 'McLaren',
    'CHYST': 'Chrysler',
    'VIRGINIA': 'N/A',
    'MAS': 'N/A',
    'HUYANDI': 'Hyundai',
    'YAHAMA': 'Yamaha',
    'ZHEJIANG': 'N/A',
    'VOLKSAGON': 'Volkswagen',
    'VOLKSWAGIN': 'Volkswagen',
    'KAIS': 'N/A',
    'HARLEYDAVIDSON': 'Harley-Davidson',
    'VOV': 'Volvo',
    'HUNDA': 'Honda',
    'MINNIAN': 'Mini',
    'HONADA': 'Honda',
    'TLOYOTA': 'Toyota',
    'JAJUAR': 'Jaguar',
    'CHRYSLER': 'Chrysler',
    'IHWJ': 'N/A',
    'VOLKVWAGON': 'Volkswagen',
    'CHEVY': 'Chevrolet',
    'TOYVAL': 'Toyota',
    'FIORD': 'Ford',
    'VANTAGE': 'Aston Martin'
}

def process_excel(file_path, output_path):
    # Carica il file Excel
    df = pd.read_excel(file_path)

    # Sostituisci i valori nella colonna 'make' usando la mappa
    df['make'] = df['make'].map(auto_makers)

    # Rimuovi i record con valore 'N/A' nella colonna 'make'
    df = df[df['make'] != 'N/A']

    # Salva il file Excel risultante
    df.to_excel(output_path, index=False)

# Esegui lo script
input_file = 'input.xlsx'  # Sostituisci con il percorso del tuo file
output_file = 'output.xlsx'  # Sostituisci con il percorso del file di output
process_excel(input_file, output_file)
