auto_models = {
  "CIVIC 5": "CIVIC",
  "CIVIC TYPE": "CIVIC TYPE R",
  "CONCERTO": "CONCERTO",
  "CRV": "CR-V",
  "HRV": "HR-V",
  "JAZZ 5": "JAZZ",
  "ACCORD": "ACCORD",
  "FRV": "FR-V",
  "INSIGHT": "INSIGHT",
  "INTEGRA": "INTEGRA",
  "JAZZ": "JAZZ",
  "LEGEND": "LEGEND",
  "LOGO": "LOGO",
  "NSX": "NSX",
  "PRELUDE": "PRELUDE",
  "S2000": "S2000",
  "SHUTTLE": "SHUTTLE",
  "STREAM": "STREAM",
  "ACCORD 5": "ACCORD",
  "ACCORD TOURER": "ACCORD TOURER",
  "CIVIC 3": "CIVIC",
  "CIVIC TYPE-R": "CIVIC TYPE R",
  "CR-V": "CR-V",
  "HR-V": "HR-V",
  "JAZZ 3": "JAZZ",
  "JAZZ/FIT": "JAZZ",
  "ACCORD COUPE'": "ACCORD COUPÉ",
  "ACCORD CPE": "ACCORD COUPÉ",
  "CIVIC CPE": "CIVIC COUPÉ",
  "CIVIC HATCH": "CIVIC",
  "CIVIC SEDAN": "CIVIC",
  "CRX": "CR-X",
  "CRX DEL SOL": "CR-X DEL SOL",
  "CRX VTEC": "CR-X",
  "DEL SOL": "CR-X DEL SOL",
  "E": "E",
  "EDIX": "EDIX",
  "FR-V": "FR-V",
  "HR": "HR-V",
  "INSPIRE": "INSPIRE",
  "INTEGRA TYPE R": "INTEGRA TYPE R",
  "JAZZ HYBRID": "JAZZ",
  "LAGREAT": "LAGREAT",
  "LEGEND COUPE": "LEGEND COUPÉ",
  "LEGEND V6": "LEGEND",
  "LIFE": "LIFE",
  "LOGO 1.4": "LOGO",
  "MDX": "MDX",
  "MOBILIO": "MOBILIO",
  "NSX COUPE": "NSX",
  "ODYSSEY": "ODYSSEY",
  "ORTHIA": "ORTHIA",
  "PARTNER": "PARTNER",
  "PRELUDE 2.0": "PRELUDE",
  "PRELUDE VTI": "PRELUDE",
  "QUINTET": "QUINTET",
  "S-MX": "S-MX",
  "S200": "S2000",
  "S660": "S660",
  "SABER": "SABER",
  "SHUTTLE HYBRID": "SHUTTLE",
  "STEPWGN": "STEPWGN",
  "STEPWAGON": "STEPWGN",
  "STREAM 1.7": "STREAM",
  "STREAM RN": "STREAM",
  "THATS": "THAT'S",
  "THAT'S": "THAT'S",
  "TODAY": "TODAY",
  "TORNEO": "TORNEO",
  "VAMOS": "VAMOS",
  "VIGOR": "VIGOR",
  "Z": "Z",
  "ZR-V": "ZR-V",
  "ZRV": "ZR-V",
  "ACCORD 3": "ACCORD",
  "BALLADE": "BALLADE",
  "BEAT": "BEAT",
  "CITY": "CITY",
  "CIVIC AERODECK": "CIVIC AERODECK",
  "CIVIC FERIO": "CIVIC FERIO",
  "CIVIC SHUTTLE": "CIVIC SHUTTLE",
  "CIVIC WAGON": "CIVIC WAGON",
  "CRX SI": "CR-X",
  "DOMANI": "DOMANI",
  "EV PLUS": "EV PLUS",
  "FIT": "JAZZ",
  "GRACE": "GRACE",
  "JAZZ CROSSTAR": "JAZZ",
  "JAZZ/FIT 5": "JAZZ",
  "LAGREAT 3.5": "LAGREAT",
  "LEGEND 3.2": "LEGEND",
  "LEGEND SH": "LEGEND",
  "LOGO 1.3": "LOGO",
  "N BOX": "N-BOX",
  "N BOX+": "N-BOX",
  "N BOX+ CUSTOM": "N-BOX",
  "N VAN": "N-VAN",
  "N-ONE": "N-ONE",
  "N-VAN": "N-VAN",
  "N-WGN": "N-WGN",
  "N360": "N360",
  "N600": "N600",
  "NBOX": "N-BOX",
  "NBOX CUSTOM": "N-BOX",
  "NBOX SLASH": "N-BOX",
  "NBOX+": "N-BOX",
  "PARTNER VAN": "PARTNER",
  "RAFAAGA": "RAFAAGA",
  "RIDGELINE": "RIDGELINE",
  "S 660": "S660",
  "S2000 TYPE S": "S2000",
  "S660 CONCEPT": "S660",
  "S660 MODULO X": "S660",
  "SHUTTLE 5": "SHUTTLE",
  "SMX": "S-MX",
  "STEP WGN": "STEPWGN",
  "STEP WGN SPADA": "STEPWGN",
  "STEPWGN SPADA": "STEPWGN",
  "THAT S": "THAT'S",
  "TODAY 0.6": "TODAY",
  "VAMOS HOBIO": "VAMOS",
  "VAMOS L": "VAMOS",
  "VEZEL": "VEZEL",
  "WRV": "WR-V",
  "WR-V": "WR-V"
}


def process_excel(file_path, output_path):
    # Carica il file Excel
    df = pd.read_excel(file_path)

    # Sostituisci i valori nella colonna 'make' usando la mappa
    df['model'] = df['model'].map(auto_models)

    # Rimuovi i record con valore 'N/A' nella colonna 'make'
    df = df[df['model'] != 'N/A']

    # Salva il file Excel risultante
    df.to_excel(output_path, index=False)

# Esegui lo script
input_file = 'input.xlsx'  # Sostituisci con il percorso del tuo file
output_file = 'output.xlsx'  # Sostituisci con il percorso del file di output
process_excel(input_file, output_file)